CREATE TABLE TB_USER (
 ID_USER SERIAL CONSTRAINT PK_USER PRIMARY KEY ,
 DS_USER varchar(30) UNIQUE NOT NULL,
 DS_PASSWORD varchar(200) NOT NULL,
 NU_RANK integer
);

CREATE TABLE TB_FORM (
 ID_FORM SERIAL CONSTRAINT PK_FORM PRIMARY KEY,
 DS_NAME_FORM varchar(30) NOT NULL,
 DS_FORM_DESCRIPTION varchar(200) NOT NULL,
 DS_LINK varchar(200) NOT NULL,
 NU_TIME integer,
 ID_USER integer NOT NULL,
 FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);

CREATE TABLE RL_ANSWER_FORM (
 ID_ANSWER_FORM SERIAL CONSTRAINT PK_ANSWER_FORM PRIMARY KEY,
 ID_FORM integer NOT NULL,
 ID_USER integer NOT NULL,
 FOREIGN KEY (ID_FORM) REFERENCES TB_FORM (ID_FORM),
 FOREIGN KEY (ID_USER) REFERENCES TB_USER (ID_USER)
);