CREATE TABLE TB_USER (
 ID_USER SERIAL CONSTRAINT PK_USER PRIMARY KEY ,
 DS_USER varchar(30) UNIQUE NOT NULL,
 DS_PASSWORD varchar(200) NOT NULL,
 NU_RANK integer
);

CREATE TABLE TB_FORM (
 ID_FORM SERIAL CONSTRAINT PK_FORM PRIMARY KEY,
 DS_NAME_FORM varchar(30) NOT NULL,
 DS_FORM_DESCRIPTION varchar(200) NOT NULL,
 DS_LINK varchar(200) NOT NULL,
 NU_TIME integer,
 ID_USER integer NOT NULL
);